---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-metrics-generator
  namespace: sample-generator
  labels:
    app: sample-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-metrics
  template:
    metadata:
      labels:
        app: sample-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: metrics-generator
          image: velmira/kcd-sofia-sample-generator:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
